Vulnerability CSV generation
maxhbr/octrc pull request #21
Opened 2022-01-11 16:55 UTC by timemmert

Given JSON files from multiple scan tools (namely syft, dependency-check and cvebintool), the newly added scripts extract vulnerability information in a common format and write them to a file.

Note: This still needs more testing, the PR was created to show the progress. The scripts have been tested individually, but the integration with Shake build system still needs more testing.

2022-01-12 07:41 UTC, maxhbr requested changes

2022-01-12 07:41 UTC, maxhbr commented on octrc-hs/src/Octrc/Syft.hs
> +      syftGrypeCSV = syftDir </> baseReportName <.> "grype.packages.csv"
maybe the naming convention should be `grype.vulns.csv`

2022-01-12 07:41 UTC, maxhbr commented on octrc-hs/src/Octrc/CveBinTool.hs
> +         mkOuts [cveBinToolJSON] [cveBinToolCSV] []
```suggestion
         mkOuts [cveBinToolJSON] [] [cveBinToolCSV]
```

2022-01-12 07:41 UTC, maxhbr commented on octrc-hs/src/Octrc/CveBinTool.hs
> +      cveBinToolCSV = cveBinToolDir </> "cve-bin-tool.csv"
maybe also follow the naming convention here

2022-01-12 07:41 UTC, maxhbr commented on octrc-hs/src/Octrc/Syft.hs
> +      grypeJSON = syftDir </> baseReportName <.> "grype.json"
good catch ...

2022-01-12 07:41 UTC, maxhbr commented on octrc-scripts/syft.vulnerabilityCsv.sh
> +#!/usr/bin/env bash
works ;)

2022-01-12 07:41 UTC, maxhbr commented on octrc-scripts/dependency-check.vulnerabilityCsv.sh
> +#!/usr/bin/env bash
I tried it for [dependency-check-report.cleaned.json.txt](https://github.com/maxhbr/octrc/files/7852570/dependency-check-report.cleaned.json.txt) but it did not produce any output (just the header, no rows)

2022-01-12 07:41 UTC, maxhbr commented on octrc-scripts/cvebintool.vulnerabilityCsv.sh
> +#!/usr/bin/env bash
works

2022-01-12 07:41 UTC, maxhbr commented on octrc-scripts/syft.vulnerabilityCsv.sh
> +jq -r '["CVE", "namespace", "dataSource", "severity", "package names", "package versions", "purl"], (.matches[] | {vulnerability, package: [.matchDetails[].searchedBy.package], artifact} | [ .vulnera
you could improve readability a lot with:
```suggestion
jq -r '["CVE", "namespace", "dataSource", "severity", "package names", "package versions", "purl"],
       (.matches[] | {vulnerability, package: [.matchDetails[].searchedBy.package], artifact}
                   | [ .vulnerability.id
                     , .vulnerability.namespace
                     , .vulnerability.dataSource
                     , .vulnerability.severity
                     , ([.package[].name] | join("|"))
                     , ([.package[].version] | join("|")), .artifact.purl]) | @csv' \
    "$json"  > "$output"
```

2022-01-18 06:49 UTC, maxhbr commented
REUSE Ci is red, some files missing headers

2022-01-18 07:36 UTC, timemmert commented on octrc-hs/src/Octrc/Syft.hs
> +      syftGrypeCSV = syftDir </> baseReportName <.> "grype.packages.csv"
Sounds good, I'll change that

2022-01-18 07:36 UTC, timemmert commented on octrc-hs/src/Octrc/CveBinTool.hs
> +         mkOuts [cveBinToolJSON] [cveBinToolCSV] []
Thanks!

2022-01-18 07:43 UTC, timemmert commented on octrc-scripts/dependency-check.vulnerabilityCsv.sh
> +#!/usr/bin/env bash
That is probably because the file you provided does not contain any vulnerability information. When testing the tool, I found out that it is quite hard to find software to scan which actually contains vulnerabilities detected by dependency-check.

I scanned Spring-boot and got the following .json: [dependency-check-report.cleaned.json.txt](https://github.com/maxhbr/octrc/files/7887103/dependency-check-report.cleaned.json.txt)

Resulting in the following csv: [dependency-check-report.vulnerabilities.csv](https://github.com/maxhbr/octrc/files/7887104/dependency-check-report.vulnerabilities.csv)

From my experience with the tool so far it is quite unlikely that all of the vulnerability analyzers have findings. I.e., for some codebases only syft produces outputs, for others only dependency-check. But that is likely not an issue with the csv generation.

2022-01-18 07:44 UTC, timemmert commented on octrc-scripts/syft.vulnerabilityCsv.sh
> +jq -r '["CVE", "namespace", "dataSource", "severity", "package names", "package versions", "purl"], (.matches[] | {vulnerability, package: [.matchDetails[].searchedBy.package], artifact} | [ .vulnera
Thanks, I will do that

2022-01-18 08:09 UTC, timemmert commented
The issues you mentioned should be fixed. Before proceeding I will scan the ubuntu docker image and spring boot to see if I can find CSV outputs for all tools.

2022-01-18 09:32 UTC, maxhbr approved these changes

2022-01-18 09:32 UTC, merged