Add license-detector data export to the octrc tool.
maxhbr/octrc pull request #6
Opened 2021-11-16 17:08 UTC by timemmert

Add a call to the license detector to octrc. The license detector scans the repository for its used licenses and outputs them in a JSON file.

2021-11-16 17:08 UTC, maxhbr approved these changes
Looks good. Let me test and probably merge that

2021-11-17 13:18 UTC, maxhbr requested changes
Some comments and please add test cases to https://github.com/maxhbr/octrc/blob/main/test:octrc.sh

2021-11-23 09:48 UTC, maxhbr requested changes

2021-11-23 09:48 UTC, maxhbr commented on test:octrc.sh
> +    echo "Test"
should that be committed?

2021-11-23 09:53 UTC, timemmert commented on test:octrc.sh
> +    echo "Test"
Nope, I will remove that...

2021-11-23 11:13 UTC, merged